### PR TITLE
fix: Properly support fill and stroke colors

### PR DESCRIPTION
**Pull request by marc2332**
Closes https://github.com/dioxus-community/dioxus-free-icons/issues/40

### CODE REVIEW

**Comment by rathod-sahaab** [comment]
Works great thanks!!

image


```toml
dioxus-free-icons = { git = "https://github.com/dioxus-community/dioxus-free-icons", branch = "fix/properly-support-fill-and-stroke-colors", features = [
  "ionicons",
  "feather",
] }
```

**Comment by rathod-sahaab** [comment]
Wait something else broke 😅

**Comment by rathod-sahaab** [comment]
image

Seem like IoFolder and IoClose aren't visible IoAdd is

**Comment by rathod-sahaab** [comment]
Older 
image

**Comment by marc2332** [comment]
Ooops, sorry @rathod-sahaab , try now 😄

**Comment by rathod-sahaab** [comment]
Shoot now IoAdd is breaking :cry:

image

**Comment by marc2332** [comment]
Try now @rathod-sahaab 🤣 I hope I didn't break anything else now!

**Comment by rathod-sahaab** [comment]
image
Everything works now!! 🥳  Thanks!! You are awesome 🥇

**Comment by marc2332** [comment]
> image Everything works now!! 🥳 Thanks!! You are awesome 🥇

Nice! I will make sure everything is fine one last time, merge and then release a new version ,asap :smile:. Thanks for the report!

**Pull request merged**
