### PR TITLE
feat: Dioxus 0.6 support

### PR DESCRIPTION
**Pull request by marc2332**

### CODE REVIEW

**Comment by marc2332** [comment]
> Just tried this out with the `0.6.0-alpha.2` version of dioxus.
> 
> It doesn't compile because there's a comma separating two `Element`s
> 
> `packages/lib/src/icon_component.rs`
> 
> ```rust
> if let Some(title_text) = props.title {
>   title {
>     "{title_text}"
>   }
> }, // <-- comma needs to be removed
> {props.icon.child_elements()}
> ```
> 
> `packages/example/src/main.rs`
> 
> ```rust
> h3 { "Frontend that scales." }
> p { "Dioxus is a portable, performant, and ergonomic framework for building cross-platform user interfaces in Rust." }, // <-- comma needs to be removed
> Icon {
>   width: 60,
>   height: 60,
>   icon: FaRust,
> }
> ```

damn it!

**Comment by marc2332** [comment]
Try now @IroncladDev (I haven't tested it myself)

**Review by IroncladDev — APPROVED** [review]
It worked like a charm

**Comment by photino** [comment]
Any plan for releasing a new version to support dioxus 0.6?

**Comment by marc2332** [comment]
> Any plan for releasing a new version to support dioxus 0.6?

done!

**Pull request merged**
