### PR TITLE
Update icons to latest versions

### PR DESCRIPTION
**Pull request by hyziri**
Added Font Awesome Bluesky icon to fa_brands_icons

### CODE REVIEW

**Comment by marc2332** [comment]
The icons are generated automatically, did you run the codegen or did you just add the icon?

**Comment by hyziri** [comment]
I added it manually, reading the README more thoroughly I see the part about the codegen now. I'll look into running it tomorrow, anything I should know prior to using it considering I've never used a codegen for an icon library before?

**Comment by hyziri** [comment]
Replaced the commit adding the Bluesky icon instead with a commit updating all icons to their latest versions using the codegen as instructed in the README.md.

- Updated all icons to latest versions using the codegen
- Fixed a typo in `packages/codegen/src/main.rs` that stated `// create feather icons` instead of `// create lucide icons`
- README.md has been updated with links to the updated icon repositories & licenses where applicable.

If there are any issues please let me know.

**Review by marc2332 — CHANGES_REQUESTED** [review]
It seems like some files got emptied? https://github.com/hyziri/dioxus-free-icons/blob/feat/dioxus-0.6/packages/lib/src/icons/hi_solid_icons.rs

**Pull request closed without merging**
